# Generated by Django 6.0.6 on 2026-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='resturant_id',
            new_name='restaurant_id',
        ),
    ]
