# Generated by Django 6.0.6 on 2026-07-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
